export interface PokemonListEntry {
  name: string;
  url: string;
}

export interface PokemonType {
  slot: number;
  type: {
    name: string;
    url: string;
  };
}

export interface PokemonStat {
  base_stat: number;
  effort: number;
  stat: {
    name: string;
    url: string;
  };
}

export interface PokemonAbility {
  is_hidden: boolean;
  slot: number;
  ability: {
    name: string;
    url: string;
  };
}

export interface PokemonDetail {
  id: number;
  name: string;
  height: number;
  weight: number;
  types: PokemonType[];
  stats: PokemonStat[];
  abilities: PokemonAbility[];
  moves: PokemonMove[];
  species: {
    name: string;
    url: string;
  };
  sprites: {
    front_default: string;
    front_shiny: string;
    other: {
      'official-artwork': {
        front_default: string;
        front_shiny: string;
      };
      dream_world: {
        front_default: string;
      };
    };
  };
}

export interface PokemonVariety {
  is_default: boolean;
  pokemon: {
    name: string;
    url: string;
  };
}

export interface PokemonSpecies {
  // FIX: Add name to PokemonSpecies type to match API response
  name: string;
  flavor_text_entries: {
    flavor_text: string;
    language: {
      name: string;
    };
  }[];
  genera: {
    genus: string;
    language: {
      name: string;
    };
  }[];
  evolution_chain: {
    url: string;
  };
  gender_rate: number;
  varieties: PokemonVariety[];
}

export interface EvolutionDetail {
  min_level: number | null;
  gender: number | null;
  held_item: { name: string } | null;
  item: { name: string } | null;
  known_move: { name: string } | null;
  known_move_type: { name: string } | null;
  location: { name: string } | null;
  min_affection: number | null;
  min_beauty: number | null;
  min_happiness: number | null;
  needs_overworld_rain: boolean;
  party_species: { name: string } | null;
  party_type: { name: string } | null;
  relative_physical_stats: number | null;
  time_of_day: string;
  trade_species: { name: string } | null;
  trigger: { name: string };
  turn_upside_down: boolean;
}

export interface EvolutionNode {
  evolution_details: EvolutionDetail[];
  species: {
    name: string;
    url: string;
  };
  evolves_to: EvolutionNode[];
}

export interface EvolutionChainResponse {
  chain: EvolutionNode;
}

export interface DamageRelations {
  double_damage_from: { name: string; url: string }[];
  half_damage_from: { name: string; url: string }[];
  no_damage_from: { name: string; url: string }[];
}

export interface TypeDetail {
  damage_relations: DamageRelations;
  name: string;
}
export interface PokemonMove {
  move: { name: string; url: string };
  version_group_details: {
    level_learned_at: number;
    move_learn_method: { name: string };
    version_group: { name: string; url: string };
  }[];
}

interface LocalizedName {
  name: string;
  language: { name: string };
}

interface EffectEntry {
  short_effect: string;
  language: { name: string };
}

export interface AbilityDetail {
  name: string;
  names: LocalizedName[];
  effect_entries: EffectEntry[];
}

export interface MoveDetail {
  name: string;
  names: LocalizedName[];
  type: { name: string };
  damage_class: { name: string } | null;
  power: number | null;
  accuracy: number | null;
  pp: number | null;
  effect_chance: number | null;
  effect_entries: EffectEntry[];
}

// Walkthrough ("detonado") content, generated by scripts/convert_guide.py
export interface GuideRun {
  t: string;
  b?: 1;
  i?: 1;
}

export interface GuideImage {
  src: string;
  w: number;
  h: number;
  fw?: number; // width as a fraction of the text column in the original layout
  card?: 1; // cropped card/table: shown on a white panel
  alt?: string;
}

export type GuideBlock =
  | { t: 'h2'; id: string; text: string; sub?: string }
  | { t: 'h3'; id: string; text: string }
  | { t: 'p'; runs: GuideRun[] }
  | { t: 'callout'; kind: 'tip' | 'warning' | 'reward' | 'trivia' | 'note'; paras: GuideRun[][] }
  | ({ t: 'img'; caption?: string } & GuideImage)
  | { t: 'gallery'; imgs: GuideImage[]; caption?: string }
  | ({ t: 'card'; alt: string } & GuideImage)
  | { t: 'caption'; text: string };

export interface GuideChapterSummary {
  n: number;
  title: string;
  part: string;
  pages: [number, number];
  sections: { id: string; text: string }[];
}

export interface GuideDownload {
  label: string;
  hint: string;
  file: string;
  pages: number;
  bytes: number;
}

export interface GuideSummary {
  slug: string;
  title: string;
  subtitle: string;
  console: string;
  description: string;
  accent: string;
  cover: string;
  chapters: number;
  pdfPages: number;
}

export interface GuideIndex extends Omit<GuideSummary, 'chapters'> {
  credit: string;
  disclaimer: string;
  license: string;
  downloads: GuideDownload[];
  chapters: GuideChapterSummary[];
}
